/*
 * This source file was generated by the Gradle 'init' task
 */
package io.wechoo

import kotlin.test.Test
import kotlin.test.assertEquals

class KonvertTest {
    @Test fun `convert to snake case`() {
        val classUnderTest = Konvert()
        val expectedResult = "snake_case"
        assertEquals(expectedResult, classUnderTest.toSnakeCase("SnakeCase"))
    }

    @Test fun `convert to camel case`() {
        val classUnderTest = Konvert()
        val expectedResult = "camelCase"
        assertEquals(expectedResult, classUnderTest.toCamelCase("camel_case"))
    }
}
